### ISSUE TITLE
Blue theme as an alternate to orange theme?

### ISSUE THREAD

**Issue by allisonrandal** [pop-os/theme#6]
Would it be possible to create a easy alternate theme that uses blue for all the highlighting instead of orange? The blue from your basic design palette (#48b9c7) is a lot more pleasant to look at.

**Comment by isantop** [comment]
Not likely. The Blue and Orange both complement each other carry significant meaning. Additionally, there are already 6 different theme variants and adding another one isn't a good idea. That said, it's not too difficult to change the colors, and since it's all open source, you're more than welcome to create a fork and set whatever colors you like! :)
